### ISSUE TITLE
[Feature Request] Embedded fuzzy-finder to find Salesforce object

### ISSUE THREAD

**Issue by sei40kr** [zaki-yama/parse-salesforce-object#14]
# What's this?

Embed fuzzy-finder so that we can search the object interactively, without specifying the path for it.

# How to implement

* [inquirer](https://github.com/SBoudrias/Inquirer.js)
* [inquirer-autocomplete-prompt](https://github.com/mokkabonna/inquirer-autocomplete-prompt)

I'm thinking of using these, but `inquirer-autocomplete-prompt` has no type definitions. So it's difficult to use.

# TODO

- [ ] Use fuzzy-finder to find the Salesforce object
- [ ] Detect `forceapp` directory automatically

**Comment by zaki-yama** [comment]
I'll close this issue because it's considered to be out of scope.
